package castle.game.model.unit;

public class Militia extends Unit {

    public Militia(){
        name = "Autogenerated name.txt";
        type = "Militia";
        //TODO redo this later.
        stats = new CombatStats(25, 2, 2, 4,
                20, 40);
        description = "Normal shitter dude.";
    }

    public Militia(String name){
        this.name = name;
        type = "Militia";
        //TODO redo this later.
        stats = new CombatStats(25, 2, 2, 4,
                20, 40);
        description = "Normal shitter dude.";
    }
}
